### ISSUE TITLE
RuntimeError: mat1 dim 1 must match mat2 dim 0

### ISSUE THREAD

**Issue by Dreamer1209** [chaineypung/Pytorch-Swin-Unet-V2#1]
我在256*256的数据集上进行分割的时候汇报了这个错误，请问是网络框架哪里需要修改吗？

**Comment by chaineypung** [comment]
是哪一行出现了错误，我去看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaineypung/Pytorch-Swin-Unet-V2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月28日(星期五) 下午5:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chaineypung/Pytorch-Swin-Unet-V2] RuntimeError: mat1 dim 1 must match mat2 dim 0 (Issue #1)





 
我在256*256的数据集上进行分割的时候汇报了这个错误，请问是网络框架哪里需要修改吗？

**Comment by chaineypung** [comment]
你有qq或者是微信吗，我的q：595037231


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaineypung/Pytorch-Swin-Unet-V2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月28日(星期五) 下午5:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chaineypung/Pytorch-Swin-Unet-V2] RuntimeError: mat1 dim 1 must match mat2 dim 0 (Issue #1)





 
我在256*256的数据集上进行分割的时候汇报了这个错误，请问是网络框架哪里需要修改吗？

**Comment by chaineypung** [comment]
你好，不好意思，把122行的in_features=2改成in_features=3就好了，之前我做的3d的，后来忘记改了，谢谢提醒！


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaineypung/Pytorch-Swin-Unet-V2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月28日(星期五) 下午5:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[chaineypung/Pytorch-Swin-Unet-V2] RuntimeError: mat1 dim 1 must match mat2 dim 0 (Issue #1)





 
我在256*256的数据集上进行分割的时候汇报了这个错误，请问是网络框架哪里需要修改吗？

**Comment by Dreamer1209** [comment]
好的，十分感谢！
